

export const Strings = {
  appName: 'Traduce Señas',
  appTagline: 'Lengua de Señas Colombiana',

  login: 'Iniciar sesión',
  register: 'Crear cuenta',
  logout: 'Cerrar sesión',
  email: 'Correo electrónico',
  password: 'Contraseña',
  confirmPassword: 'Confirmar contraseña',
  name: 'Nombre completo',
  age: 'Edad',
  forgotPassword: '¿Olvidaste tu contraseña?',
  noAccount: '¿No tienes cuenta? ',
  hasAccount: '¿Ya tienes cuenta? ',
  terms: 'Acepto los términos y condiciones',
  loginWithGoogle: 'Continuar con Google',

  home: 'Inicio',
  translation: 'Traducir',
  lexicon: 'Léxico',
  history: 'Historial',
  profile: 'Perfil',

  welcomeBack: 'Bienvenido de nuevo',
  quickAccess: 'Acceso rápido',
  recentTranslations: 'Traducciones recientes',
  seeAll: 'Ver todo',

  modeCamera: 'Seña → Texto',
  modeCameraDesc: 'Usa la cámara para traducir señas',
  modeText: 'Texto → Seña',
  modeTextDesc: 'Escribe para ver la seña',
  modeVoice: 'Voz → Seña',
  modeVoiceDesc: 'Habla para traducir',

  startCamera: 'Iniciar cámara',
  stopCamera: 'Detener',
  enterText: 'Escribe aquí...',
  translate: 'Traducir',
  startRecording: 'Presiona para hablar',
  stopRecording: 'Soltar para traducir',
  result: 'Resultado',
  saveTranslation: 'Guardar traducción',
  clearText: 'Limpiar',
  copyResult: 'Copiar resultado',
  translating: 'Traduciendo...',
  detecting: 'Detectando seña...',
  listening: 'Escuchando...',

  searchSigns: 'Buscar señas...',
  allCategories: 'Todas',
  letters: 'Letras',
  numbers: 'Números',
  words: 'Palabras',
  phrases: 'Frases',
  noResults: 'No se encontraron resultados',
  viewSign: 'Ver seña',

  deleteTranslation: 'Eliminar',
  confirmDelete: '¿Eliminar esta traducción?',
  emptyHistory: 'No hay traducciones guardadas',
  startTranslating: 'Comienza a traducir para ver tu historial',

  editProfile: 'Editar perfil',
  language: 'Idioma',
  theme: 'Tema',
  themeLight: 'Claro',
  themeDark: 'Oscuro',
  notifications: 'Notificaciones',
  privacyPolicy: 'Política de privacidad',
  termsConditions: 'Términos y condiciones',
  about: 'Acerca de',

  noNotifications: 'No tienes notificaciones',
  markAsRead: 'Marcar como leída',

  requiredField: 'Este campo es obligatorio',
  invalidEmail: 'Correo electrónico inválido',
  passwordMismatch: 'Las contraseñas no coinciden',
  shortPassword: 'La contraseña debe tener al menos 6 caracteres',
  cameraPermission: 'Se necesita permiso de cámara',
  micPermission: 'Se necesita permiso de micrófono',
  genericError: 'Ocurrió un error. Intenta de nuevo.',
  networkError: 'Sin conexión a internet',

  cancel: 'Cancelar',
  confirm: 'Confirmar',
  save: 'Guardar',
  delete: 'Eliminar',
  edit: 'Editar',
  close: 'Cerrar',
  back: 'Atrás',
  next: 'Siguiente',
  done: 'Listo',
  loading: 'Cargando...',
};
